sudo: false
language: java
jdk:
  - openjdk8
  - openjdk11
script:
  - ./gradlew publishToMavenLocal -i -s
  - cd git-changelog-gradle-plugin-example && ./gradlew generateChangelogs
notifications:
  email: false
